defmodule Raxol.Payments.Xochi.StealthConformanceTest do
  @moduledoc """
  Byte-for-byte conformance of the stealth scheme against a reference
  implementation (viem / `@scopelift/stealth-address-sdk` or the Xochi TS
  shared lib).

  This is the interop contract: the Xochi-specific key derivation and the
  ERC-5564 stealth address derivation must match the reference exactly, or a
  payment generated by one side is undiscoverable by the other.

  The fixture is a JSON array of vectors. Resolve its path with the
  `STEALTH_VECTORS_PATH` env var. Vector shapes:

      {"type": "derive_keys", "signature": "0x..",
       "spending_priv": "0x..", "spending_pub": "0x..",
       "viewing_priv": "0x..", "viewing_pub": "0x.."}

      {"type": "generate", "spending_pub": "0x..", "viewing_pub": "0x..",
       "ephemeral_priv": "0x..", "expected_stealth_address": "0x..",
       "expected_ephemeral_pub": "0x..", "expected_view_tag": 123}

  Generate the fixture from the reference SDK and point `STEALTH_VECTORS_PATH`
  at it. Tagged `:stealth_conformance` and skipped by default.
  """

  use ExUnit.Case, async: true

  alias Raxol.Payments.Xochi.Stealth

  @moduletag :stealth_conformance

  @vectors_path System.get_env("STEALTH_VECTORS_PATH")

  if is_nil(@vectors_path) do
    @moduletag skip: "set STEALTH_VECTORS_PATH to the reference stealth vectors fixture"
  end

  setup do
    case @vectors_path do
      nil -> :ok
      path -> {:ok, vectors: path |> File.read!() |> Jason.decode!()}
    end
  end

  test "derive_keys matches the reference byte-for-byte", %{vectors: vectors} do
    for %{"type" => "derive_keys"} = v <- vectors do
      assert {:ok, keys} = Stealth.derive_keys(v["signature"])
      {sp_priv, sp_pub} = keys.spending
      {vp_priv, vp_pub} = keys.viewing

      assert hex(sp_priv) == norm(v["spending_priv"]), "spending_priv (#{v["name"]})"
      assert hex(sp_pub) == norm(v["spending_pub"]), "spending_pub (#{v["name"]})"
      assert hex(vp_priv) == norm(v["viewing_priv"]), "viewing_priv (#{v["name"]})"
      assert hex(vp_pub) == norm(v["viewing_pub"]), "viewing_pub (#{v["name"]})"
    end
  end

  test "generate matches the reference stealth address and view tag", %{vectors: vectors} do
    for %{"type" => "generate"} = v <- vectors do
      meta = %{
        spending_pub_key: bin(v["spending_pub"]),
        viewing_pub_key: bin(v["viewing_pub"]),
        chain_id: 1
      }

      assert {:ok, s} = Stealth.generate(meta, bin(v["ephemeral_priv"]))

      assert String.downcase(s.stealth_address) == String.downcase(v["expected_stealth_address"]),
             "stealth_address (#{v["name"]})"

      assert hex(s.ephemeral_pub_key) == norm(v["expected_ephemeral_pub"]),
             "ephemeral_pub (#{v["name"]})"

      assert s.view_tag == v["expected_view_tag"], "view_tag (#{v["name"]})"
    end
  end

  defp bin("0x" <> hex), do: Base.decode16!(hex, case: :mixed)
  defp bin(hex), do: Base.decode16!(hex, case: :mixed)

  defp hex(bytes), do: Base.encode16(bytes, case: :lower)

  defp norm("0x" <> hex), do: String.downcase(hex)
  defp norm(hex), do: String.downcase(hex)
end
