defmodule Raxol.Payments.Protocols.Permit2Test do
  use ExUnit.Case, async: true

  alias Raxol.Payments.Protocols.Permit2

  # All vectors generated by ethers v5 via
  # `riddler-client/src/index.js sign-permit2 --chain base --quote ...`
  # with PRIVATE_KEY=0x0000...0001 at commit b870aa2. Domain, message, digest,
  # signature, and signed_object values are captured byte-for-byte from the
  # CLI's RESULT_JSON output.
  @canonical_address "0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf"

  @canonical_quote %{
    "request" => %{
      "inputAmount" => "1000000",
      "refundAddress" => @canonical_address,
      "inputToken" => "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    },
    "quoteExpires" => 1_900_000_000,
    "gasless" => %{
      "to" => "0xc6E555dfcC47e4A3bfecd6879570044ADc0270ff",
      "nonce" => "1",
      "orderId" => "0xdeadbeef00000000000000000000000000000000000000000000000000000000",
      "type" => "permit2"
    }
  }

  @canonical_digest "0x45ea6009dda9a4c02d810fa2d3e4b6e9f01759e604183fe79fe34f42a98c6518"
  @canonical_signed_object "0x000000000000000000000000833589fcd6edb6e08f4c7c32d4f71b54bda0291300000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000c6e555dfcc47e4a3bfecd6879570044adc0270ff000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000713fb300"

  defmodule StaticWallet do
    @moduledoc false
    @behaviour Raxol.Payments.Wallet
    @impl true
    def address, do: "0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf"
    @impl true
    def chain_id, do: 8453
    @impl true
    def sign_message(_msg), do: {:ok, <<0::512>>}
    @impl true
    def sign_typed_data(domain, types, message) do
      Process.put(:permit2_domain, domain)
      Process.put(:permit2_types, types)
      Process.put(:permit2_message, message)
      # Return a fixed sentinel; tests assert on the digest/signed_object,
      # not on this signature value.
      {:ok, <<0xAA::8, 0::512>>}
    end

    @impl true
    def sign_hash(_digest), do: {:ok, <<0::520>>}
  end

  describe "Protocol behaviour stubs" do
    test "name/0" do
      assert Permit2.name() == "Permit2"
    end

    test "detect?/2 always returns false (not a 402 protocol)" do
      refute Permit2.detect?(402, [{"payment-required", "x"}])
      refute Permit2.detect?(200, [])
    end

    test "parse_challenge/1 returns :not_a_402_protocol" do
      assert {:error, :not_a_402_protocol} = Permit2.parse_challenge([])
    end

    test "build_payment/2 returns :not_a_402_protocol" do
      assert {:error, :not_a_402_protocol} = Permit2.build_payment(%{}, StaticWallet)
    end

    test "parse_receipt/1 returns :not_a_402_protocol" do
      assert {:error, :not_a_402_protocol} = Permit2.parse_receipt([])
    end

    test "amount/1 reads input_amount" do
      assert Decimal.equal?(Permit2.amount(%{input_amount: "1000000"}), Decimal.new("1000000"))
      assert Decimal.equal?(Permit2.amount(%{input_amount: 1_000_000}), Decimal.new("1000000"))
      assert Decimal.equal?(Permit2.amount(%{}), Decimal.new("0"))
    end
  end

  describe "domain and types" do
    test "verifying_contract is the universal Permit2 address" do
      assert Permit2.verifying_contract() ==
               "0x000000000022D473030F116dDEE9F6B43aC78BA3"
    end

    test "types map matches CLI signing.js byte-for-byte" do
      types = Permit2.types()

      assert types["PermitWitnessTransferFrom"] == [
               {"permitted", "TokenPermissions"},
               {"spender", "address"},
               {"nonce", "uint256"},
               {"deadline", "uint256"},
               {"witness", "OriginPullWitness"}
             ]

      assert types["TokenPermissions"] == [
               {"token", "address"},
               {"amount", "uint256"}
             ]

      assert types["OriginPullWitness"] == [{"orderId", "bytes32"}]
    end
  end

  describe "sign_quote/3" do
    test "produces an EIP-712 digest matching ethers v5 byte-for-byte" do
      assert {:ok, result} = Permit2.sign_quote(@canonical_quote, 8453, StaticWallet)
      assert result.digest == @canonical_digest
    end

    test "produces a signed_object matching the CLI's offset-stripped output" do
      assert {:ok, result} = Permit2.sign_quote(@canonical_quote, 8453, StaticWallet)
      assert result.signed_object == @canonical_signed_object
    end

    test "domain has no version field and uses the universal Permit2 contract" do
      assert {:ok, %{domain: domain}} =
               Permit2.sign_quote(@canonical_quote, 8453, StaticWallet)

      assert domain.name == "Permit2"
      assert domain.chainId == 8453
      assert domain.verifyingContract == "0x000000000022D473030F116dDEE9F6B43aC78BA3"
      refute Map.has_key?(domain, :version)
    end

    test "passes the domain, types and message through to the wallet" do
      assert {:ok, _} = Permit2.sign_quote(@canonical_quote, 8453, StaticWallet)

      assert Process.get(:permit2_domain).name == "Permit2"
      assert is_map(Process.get(:permit2_types))
      assert Map.has_key?(Process.get(:permit2_message), "permitted")
    end

    test "atom-keyed quote works the same as string-keyed quote" do
      atom_quote = %{
        request: %{
          inputAmount: "1000000",
          refundAddress: @canonical_address,
          inputToken: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
        },
        quoteExpires: 1_900_000_000,
        gasless: %{
          to: "0xc6E555dfcC47e4A3bfecd6879570044ADc0270ff",
          nonce: "1",
          orderId: "0xdeadbeef00000000000000000000000000000000000000000000000000000000",
          type: "permit2"
        }
      }

      assert {:ok, result} = Permit2.sign_quote(atom_quote, 8453, StaticWallet)
      assert result.digest == @canonical_digest
      assert result.signed_object == @canonical_signed_object
    end

    test "missing required field returns an error" do
      bad_quote =
        put_in(@canonical_quote["gasless"], Map.delete(@canonical_quote["gasless"], "orderId"))

      assert {:error, {:missing_quote_field, :orderId}} =
               Permit2.sign_quote(bad_quote, 8453, StaticWallet)
    end
  end

  describe "Protocol.resolve/1" do
    test "resolves :permit2 to this module" do
      assert Raxol.Payments.Protocol.resolve(:permit2) == Permit2
    end
  end
end
