defmodule RaxolPlayground.RecordedFrames do
  @moduledoc """
  Recorded terminal frames served statically: the landing hero's Counter
  frames and one rendered preview per gallery demo.

  Generated by `scripts/gen_landing_frames.exs` at the repo root (real
  `Raxol.Headless` sessions rendered through `TerminalBridge.buffer_to_html/2`)
  and committed under `priv/hero_frames/` and `priv/demo_previews/`. Embedded
  at compile time so the dead render before the LiveView socket connects
  already carries frame one and every gallery preview.
  """

  hero_dir = Path.expand("../../priv/hero_frames", __DIR__)
  preview_dir = Path.expand("../../priv/demo_previews", __DIR__)

  # frame_0..frame_9 sort lexically; pad the generator's names before
  # recording a sequence that reaches double digits.
  hero_paths =
    hero_dir
    |> File.ls!()
    |> Enum.sort()
    |> Enum.map(&Path.join(hero_dir, &1))

  for path <- hero_paths do
    @external_resource path
  end

  @hero_frames Enum.map(hero_paths, &File.read!/1)

  preview_paths =
    preview_dir
    |> File.ls!()
    |> Enum.sort()
    |> Enum.map(&Path.join(preview_dir, &1))

  for path <- preview_paths do
    @external_resource path
  end

  @previews Map.new(preview_paths, fn path ->
              {Path.basename(path, ".html"), File.read!(path)}
            end)

  @doc "The hero Counter frames, in playback order."
  @spec hero_frames() :: [String.t()]
  def hero_frames, do: @hero_frames

  @doc "Rendered preview frame for a catalog demo name, or nil."
  @spec preview(String.t()) :: String.t() | nil
  def preview(name), do: Map.get(@previews, slug(name))

  @doc "The slug a demo name is stored under (mirrors the generator)."
  @spec slug(String.t()) :: String.t()
  def slug(name) do
    name
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9]+/, "_")
    |> String.trim("_")
  end
end
