defmodule RaxolPlayground.RecordedFrames do
  @moduledoc """
  Recorded terminal frames served statically: the landing hero's switchable
  examples and one rendered preview per gallery demo.

  Generated by `scripts/gen_landing_frames.exs` at the repo root (real
  `Raxol.Headless` sessions rendered through `TerminalBridge.buffer_to_html/2`)
  and committed under `priv/hero_frames/` and `priv/demo_previews/`. Embedded
  at compile time so the dead render before the LiveView socket connects
  already carries frame one and every gallery preview.

  An example directory holds its terminal frames plus two surface artifacts
  projected from the frame-zero render: `surface.ansi` (the bytes the SSH
  surface writes) and `surface.mcp.json` (the tree the MCP surface serves).
  The browser surface needs no artifact, since frame zero is already the
  LiveView encoding.
  """

  alias RaxolPlayground.SurfaceSource

  hero_dir = Path.expand("../../priv/hero_frames", __DIR__)
  preview_dir = Path.expand("../../priv/demo_previews", __DIR__)

  # One directory per hero example. frame_0..frame_9 sort lexically; pad the
  # generator's names before recording a sequence that reaches double digits.
  hero_examples =
    hero_dir
    |> File.ls!()
    |> Enum.sort()
    |> Enum.filter(&File.dir?(Path.join(hero_dir, &1)))

  # Matched by name: the surface artifacts share this directory, and folding
  # one into the playback list would put an ANSI dump where a frame belongs.
  hero_paths =
    Map.new(hero_examples, fn name ->
      dir = Path.join(hero_dir, name)

      paths =
        dir
        |> Path.join("frame_*.html")
        |> Path.wildcard()
        |> Enum.sort()

      {name, paths}
    end)

  surface_paths =
    Map.new(hero_examples, fn name ->
      dir = Path.join(hero_dir, name)

      {name,
       %{
         ansi: Path.join(dir, "surface.ansi"),
         mcp: Path.join(dir, "surface.mcp.json")
       }}
    end)

  for {_name, paths} <- hero_paths, path <- paths do
    @external_resource path
  end

  for {_name, %{ansi: ansi, mcp: mcp}} <- surface_paths, path <- [ansi, mcp] do
    @external_resource path
  end

  @hero_frames Map.new(hero_paths, fn {name, paths} ->
                 {name, Enum.map(paths, &File.read!/1)}
               end)

  # The browser artifact is frame zero itself, so that pane shows the source
  # of the markup the terminal pane renders and the two cannot disagree.
  @hero_artifacts Map.new(surface_paths, fn {name, %{ansi: ansi, mcp: mcp}} ->
                    {name,
                     %{
                       browser:
                         hero_paths
                         |> Map.fetch!(name)
                         |> List.first()
                         |> File.read!(),
                       ssh: File.read!(ansi),
                       mcp: File.read!(mcp)
                     }}
                  end)

  # Derived once: the artifacts are compile-time constants, so the line
  # breaking, clamping, escaping and colouring are too.
  @hero_surfaces Map.new(@hero_artifacts, fn {name, artifacts} ->
                   panes =
                     Map.new(artifacts, fn
                       # SSH is painted, not listed. The other two surfaces
                       # carry structured text a reader reads line by line, so
                       # they are broken to a line budget with a marker. This
                       # one carries a picture, so it keeps its own grid whole
                       # and the CSS fits the type to it, exactly as the
                       # terminal pane beside it does.
                       {:ssh, artifact} ->
                         rows = SurfaceSource.ansi_rows(artifact)

                         {:ssh,
                          %{
                            html: SurfaceSource.ansi_html(rows),
                            grid: SurfaceSource.ansi_grid(rows)
                          }}

                       {surface, artifact} ->
                         lines =
                           case surface do
                             :browser -> SurfaceSource.dom_lines(artifact)
                             :mcp -> SurfaceSource.json_lines(artifact)
                           end

                         kind = %{browser: :dom, mcp: :json}[surface]

                         clamped =
                           lines
                           |> SurfaceSource.wrap()
                           |> SurfaceSource.clamp(artifact)

                         {surface,
                          %{
                            html: SurfaceSource.to_html(clamped, kind),
                            lines: length(clamped)
                          }}
                     end)

                   {name, panes}
                 end)

  preview_paths =
    preview_dir
    |> File.ls!()
    |> Enum.sort()
    |> Enum.map(&Path.join(preview_dir, &1))

  for path <- preview_paths do
    @external_resource path
  end

  @previews Map.new(preview_paths, fn path ->
              {Path.basename(path, ".html"), File.read!(path)}
            end)

  @doc "Recorded frames for one hero example, in playback order."
  @spec hero_frames(String.t()) :: [String.t()]
  def hero_frames(example), do: Map.get(@hero_frames, example, [])

  @doc "Every hero example name that has recorded frames."
  @spec hero_examples() :: [String.t()]
  def hero_examples, do: @hero_frames |> Map.keys() |> Enum.sort()

  @doc """
  Pane markup for one hero example on one non-terminal surface, derived from
  that example's recorded artifact by `RaxolPlayground.SurfaceSource`.
  """
  @spec hero_surface(String.t(), surface()) :: String.t()
  def hero_surface(example, surface) do
    example |> pane(surface) |> Map.get(:html, "")
  end

  @doc """
  How many lines that pane holds. The CSS sizes type from this, so a short
  viewport shrinks the type rather than cutting the truncation marker.
  """
  @spec hero_surface_lines(String.t(), surface()) :: pos_integer()
  def hero_surface_lines(example, surface) do
    example |> pane(surface) |> Map.get(:lines, 1)
  end

  @doc """
  Rows and columns in the decoded SSH pane, in painted characters.

  The same two-axis fit the terminal frames get: the recording's grid is fixed
  and the pane's is not, so the type follows the frame rather than the frame
  being cut to a line budget it never fit.
  """
  @spec hero_ssh_grid(String.t()) :: %{rows: pos_integer(), cols: pos_integer()}
  def hero_ssh_grid(example) do
    example |> pane(:ssh) |> Map.get(:grid, %{rows: 1, cols: 1})
  end

  defp pane(example, surface) do
    @hero_surfaces |> Map.get(example, %{}) |> Map.get(surface, %{})
  end

  @doc """
  Rows and columns in one recorded terminal frame.

  The CSS sizes the frame's type from both, so the frame grows to fill the
  pane it is given and shrinks to fit a short one, instead of sitting at a
  fixed size with dead space beside it.
  """
  @spec hero_frame_grid(String.t()) :: %{
          rows: pos_integer(),
          cols: pos_integer()
        }
  def hero_frame_grid(example) do
    case hero_frames(example) do
      [frame | _] -> grid(frame)
      [] -> %{rows: 1, cols: 1}
    end
  end

  # Measured off the frame's own text: the recording geometry lives in the
  # generator, and a second copy of it here would be free to drift.
  defp grid(frame) do
    lines =
      frame
      |> String.replace(~r/<[^>]*>/, "")
      |> unescape()
      |> String.split("\n")
      # The encoder closes with a newline before `</pre>`, so the last split is
      # the closing tag rather than a row.
      |> Enum.drop(-1)

    %{
      rows: max(length(lines), 1),
      cols:
        lines |> Enum.map(&String.length/1) |> Enum.max(fn -> 1 end) |> max(1)
    }
  end

  defp unescape(text) do
    # &amp; last, or an escaped &amp;lt; would come back as a literal <.
    text
    |> String.replace("&lt;", "<")
    |> String.replace("&gt;", ">")
    |> String.replace("&quot;", "\"")
    |> String.replace("&#39;", "'")
    |> String.replace("&amp;", "&")
  end

  @doc """
  The recorded artifact a pane was derived from, verbatim. Exposed so a test
  can check every line the pane shows against it.
  """
  @spec hero_artifact(String.t(), surface()) :: String.t()
  def hero_artifact(example, surface) do
    @hero_artifacts |> Map.get(example, %{}) |> Map.get(surface, "")
  end

  @typedoc "A hero surface other than the terminal, which plays frames."
  @type surface :: :browser | :ssh | :mcp

  @doc "Rendered preview frame for a catalog demo name, or nil."
  @spec preview(String.t()) :: String.t() | nil
  def preview(name), do: Map.get(@previews, slug(name))

  @doc "The slug a demo name is stored under (mirrors the generator)."
  @spec slug(String.t()) :: String.t()
  def slug(name) do
    name
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9]+/, "_")
    |> String.trim("_")
  end
end
