FROM elixir:1.20.2-otp-29@sha256:c915d900894e1d664cd8ed72fd2c38fce72b612cc1757d57f86a0cc62e62dd79

# Install basic dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  autoconf \
  m4 \
  libncurses5-dev \
  libssl-dev \
  libgl1-mesa-dev \
  libglu1-mesa-dev \
  libpng-dev \
  openssl \
  git \
  curl \
  wget \
  unzip \
  nodejs \
  npm \
  yarn \
  && rm -rf /var/lib/apt/lists/*

# Set up environment
ENV MIX_HOME=/root/.mix
ENV HEX_HOME=/root/.hex

# Install Hex and Rebar
RUN mix local.hex --force && \
  mix local.rebar --force

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]
