defmodule Mix.Tasks.RaxolAcp.DeriveCaps do
  @shortdoc "Derive TransferOffering destination caps from live solver balances"

  @moduledoc """
  Query the Xochi/Riddler solver's on-chain token balances and emit a
  `:destination_caps` (per-order) + `:destination_capacity` (rolling aggregate)
  config for `Raxol.ACP.Xochi.TransferOffering`, so the launch liquidity gate is
  data-derived rather than hand-maintained. The same reads power the runtime
  `Raxol.ACP.Xochi.CapacityRefresher`; both share `Raxol.ACP.Xochi.CapacityDeriver`.

      mix raxol_acp.derive_caps
      mix raxol_acp.derive_caps --solver 0x97D4... --order-frac 0.2 \\
        --aggregate-frac 0.9 --min-usd 50 --output config/destination_caps.exs

  For each `{chain, token}` in `Raxol.Payments.Assets.evm_tokens/0` it reads
  `balanceOf(solver)` and sets per-order = `floor(balance x --order-frac)`,
  aggregate = `floor(balance x --aggregate-frac)`; a corridor worth less than
  `--min-usd` (stables = \\$1, WETH = `--eth-price`) is CLOSED (`0`).

  RPC per chain: `DERIVE_RPC_<chain_id>` env, else a public default; Robinhood
  (4663) needs `DERIVE_RPC_4663`. A chain with no reachable RPC is skipped
  (stderr), never silently dropped. Output goes to stdout or `--output <path>`.
  """

  use Mix.Task

  alias Raxol.ACP.Xochi.CapacityDeriver

  @switches [
    solver: :string,
    order_frac: :float,
    aggregate_frac: :float,
    min_usd: :float,
    eth_price: :float,
    output: :string
  ]

  @impl Mix.Task
  def run(argv) do
    {opts, _rest, _invalid} = OptionParser.parse(argv, switches: @switches)
    {:ok, _} = Application.ensure_all_started(:req)

    order_frac = Keyword.get(opts, :order_frac, 0.2)
    aggregate_frac = Keyword.get(opts, :aggregate_frac, 0.9)
    min_usd = Keyword.get(opts, :min_usd, 50.0)

    rows = CapacityDeriver.derive(opts)
    output = render(rows, order_frac, aggregate_frac, min_usd)

    case Keyword.get(opts, :output) do
      nil ->
        Mix.shell().info(output)

      path ->
        File.write!(path, output)
        Mix.shell().info("wrote #{path} (#{length(rows)} corridors)")
    end
  end

  defp render(rows, order_frac, aggregate_frac, min_usd) do
    sorted = Enum.sort_by(rows, fn r -> {r.symbol, r.chain} end)

    caps =
      Enum.map_join(sorted, "\n", &entry(&1, CapacityDeriver.cap_value(&1, order_frac, min_usd)))

    capacity =
      Enum.map_join(
        sorted,
        "\n",
        &entry(&1, CapacityDeriver.cap_value(&1, aggregate_frac, min_usd))
      )

    """
    import Config

    # Generated by `mix raxol_acp.derive_caps` -- point-in-time snapshot, review before use.
    # per-order = balance x #{order_frac}; aggregate = balance x #{aggregate_frac};
    # corridor closed (0) when worth < $#{min_usd}.

    config :raxol_acp, :destination_caps, %{
    #{caps}
    }

    config :raxol_acp, :destination_capacity, %{
    #{capacity}
    }
    """
  end

  defp entry(row, value) do
    "  {#{row.chain}, \"#{row.token}\"} => #{value},  # #{row.symbol} #{usd(row.usd)}"
  end

  defp usd(usd) when usd >= 1, do: "$#{:erlang.float_to_binary(usd, decimals: 2)}"
  defp usd(usd), do: "$#{:erlang.float_to_binary(usd, decimals: 4)}"
end
