defmodule Raxol.Broker.Tools.Generator do
  @moduledoc """
  Renders `Raxol.Broker.Tools.<Family>` modules from the capture: one module
  per family, one function per `:read` tool, each with a `@spec` and a doc
  listing its arguments. Pure and deterministic, so `mix
  raxol.broker.gen.tools` is idempotent and a stale checked-in file is a
  test failure.
  """

  alias Raxol.Broker.Tools.Catalog

  @dir "lib/raxol/broker/tools/generated"

  # First match wins, so the narrower families come first.
  @families [
    {"Crypto", ~r/crypto|currency_pair/},
    {"Options", ~r/option/},
    {"AdvancedOrders", ~r/advanced/},
    {"Scanner", ~r/scan/},
    {"Alerts", ~r/alert/},
    {"Watchlists", ~r/watchlist/},
    {"Legend", ~r/legend/},
    {"Equities", ~r/equity_(?:orders|positions|tax_lots)/},
    {"Account", ~r/account|portfolio|pnl|margin/},
    {"MarketData", ~r//}
  ]

  @doc "The directory generated files live in, relative to the package root."
  @spec dir() :: String.t()
  def dir, do: @dir

  @doc "`%{relative_path => contents}` for every generated module."
  @spec render([map()]) :: %{String.t() => String.t()}
  def render(tools \\ Catalog.recorded_tools()) do
    tools
    |> Enum.filter(&(Catalog.classify(&1["name"], &1) == :read))
    |> Enum.sort_by(& &1["name"])
    |> Enum.group_by(&family(&1["name"]))
    |> Map.new(fn {family, members} ->
      {Path.join(@dir, Macro.underscore(family) <> ".ex"), module(family, members)}
    end)
  end

  @doc "The family module a tool name belongs to."
  @spec family(String.t()) :: String.t()
  def family(name) do
    Enum.find_value(@families, fn {family, pattern} ->
      if Regex.match?(pattern, name), do: family
    end)
  end

  defp module(family, tools) do
    """
    # Generated by `mix raxol.broker.gen.tools` from priv/robinhood/tools_list.json.
    # Do not edit; regenerate.
    defmodule Raxol.Broker.Tools.#{family} do
      @moduledoc "Read tools of the #{family} family, generated from the capture."

      #{Enum.map_join(tools, "\n\n", &function/1)}
    end
    """
    |> Code.format_string!()
    |> IO.iodata_to_binary()
    |> Kernel.<>("\n")
  end

  defp function(tool) do
    name = tool["name"]
    fun = function_name(name)

    """
    @doc #{doc(tool)}
    @spec #{fun}(GenServer.server(), map()) :: {:ok, map()} | {:error, term()}
    def #{fun}(client, args \\\\ %{}), do: Raxol.Broker.Tools.call(client, #{inspect(name)}, args)
    """
  end

  defp function_name(name) do
    fun = String.replace(name, ~r/[^A-Za-z0-9_]/, "_")
    if fun =~ ~r/\A[a-z_]/, do: fun, else: "t_" <> fun
  end

  # A `~S` heredoc: no interpolation or escapes, so text from the server stays
  # inert. Text containing `"""` would end it early and is quoted instead.
  defp doc(tool) do
    text =
      [description(tool), arguments(tool["inputSchema"] || %{})]
      |> Enum.reject(&(&1 == ""))
      |> Enum.join("\n\n")

    if String.contains?(text, ~s(""")),
      do: inspect(text, printable_limit: :infinity),
      else: ~s(~S"""\n) <> text <> ~s(\n""")
  end

  defp description(tool) do
    tool
    |> Map.get("description", "")
    |> String.split(~r/\n\s*\n/, parts: 2)
    |> hd()
    |> String.trim()
  end

  defp arguments(schema) do
    required = Map.get(schema, "required", [])

    case Map.get(schema, "properties", %{}) |> Enum.sort() do
      [] ->
        "Takes no arguments."

      properties ->
        lines = Enum.map(properties, &argument_line(&1, required))
        Enum.join(["Arguments (string keys):" | lines], "\n")
    end
  end

  defp argument_line({key, sub}, required) do
    flag = if key in required, do: "required", else: "optional"
    "  * `#{key}` (#{flag}, #{type(sub)})"
  end

  defp type(%{"type" => "array", "items" => items}), do: "array of #{type(items)}"
  defp type(%{"type" => types}) when is_list(types), do: Enum.join(types, " | ")
  defp type(%{"type" => type}) when is_binary(type), do: type
  defp type(_schema), do: "any"
end
