defmodule Mix.Tasks.Raxol.Docs.Tools do
  @shortdoc "Generate the LLM tool/action catalog from action metadata"

  @moduledoc """
  Regenerate `docs/reference/TOOL_CATALOG.md`, a catalog of every LLM-callable
  Agent Action, introspected from each action's `__action_meta__/0`.

      cd packages/raxol_payments
      mix raxol.docs.tools

  This task lives in `raxol_payments` because that package depends on
  `raxol_agent` at compile time, so both packages' action modules are on the
  code path here. The catalog is derived from the live metadata (name,
  description, input schema, sensitivity), so it cannot drift from the actual
  dispatchable surface. It is deterministic: run it twice and the output is
  byte-identical.
  """

  use Mix.Task

  @impl true
  def run(_args) do
    actions = load_actions()
    metas = Enum.map(actions, &meta/1) |> Enum.sort_by(& &1.name)
    {agent, payments} = Enum.split_with(metas, &(&1.group == :agent))

    doc = build_doc(agent, payments)
    path = Path.join(repo_root(), "docs/reference/TOOL_CATALOG.md")
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, doc)

    sensitive = Enum.count(metas, & &1.sensitive)

    Mix.shell().info([
      :green,
      "wrote ",
      :reset,
      "docs/reference/TOOL_CATALOG.md (#{length(metas)} tools, #{sensitive} sensitive)"
    ])
  end

  # --- introspection --------------------------------------------------------

  defp load_actions do
    modules =
      Raxol.Agent.Actions.Vfs.actions() ++
        Raxol.Agent.Actions.Fs.all() ++
        Raxol.Agent.Actions.Code.all() ++
        Raxol.Agent.Actions.Memory.actions() ++
        Raxol.Agent.Actions.Skills.actions() ++
        Raxol.Agent.Actions.Task.all() ++
        [Raxol.Agent.Actions.SessionSearch] ++
        Raxol.Payments.Actions.Payments.actions()

    modules
    |> Enum.uniq()
    |> Enum.filter(fn mod ->
      Code.ensure_loaded?(mod) and function_exported?(mod, :__action_meta__, 0)
    end)
  end

  defp meta(mod) do
    m = mod.__action_meta__()

    %{
      name: m.name,
      description: m |> Map.get(:description, "") |> one_line(),
      params: render_params(Map.get(m, :input_schema, [])),
      sensitive: Map.get(m, :sensitive, false) == true,
      group: if(String.starts_with?(inspect(mod), "Raxol.Payments"), do: :payments, else: :agent)
    }
  end

  defp render_params([]), do: "(none)"

  defp render_params(schema) when is_list(schema) do
    Enum.map_join(schema, ", ", fn {name, spec} ->
      req = if Keyword.get(spec, :required, false), do: ", required", else: ""
      "`#{name}` (#{type_str(spec[:type])}#{req})"
    end)
  end

  defp render_params(_), do: "(none)"

  defp type_str({:list, inner}), do: "list of #{type_str(inner)}"
  defp type_str(type) when is_atom(type) and not is_nil(type), do: Atom.to_string(type)
  defp type_str(_), do: "any"

  # --- rendering ------------------------------------------------------------

  defp build_doc(agent, payments) do
    total = length(agent) + length(payments)
    sensitive = Enum.count(agent ++ payments, & &1.sensitive)

    """
    # Tool / Action Catalog

    Every LLM-callable Agent Action, with its parameters and authorization tier.
    This catalog is generated by `mix raxol.docs.tools` (run from
    `packages/raxol_payments`), introspected from each action's
    `__action_meta__/0`, so it cannot drift from the actual dispatchable surface.

    Total: #{total} tools, #{sensitive} sensitive.

    ## Authorization

    Read-only tools always run. A tool marked **sensitive** is denied by default
    (`Raxol.Agent.ToolPolicy.deny_sensitive/0`) unless the surface installs a
    `:tool_authorizer`, which resolves it through the ALLOW/ASK/DENY
    [Authorization engine](../features/AGENT_FRAMEWORK.md#authorization-allowaskdeny).
    The [Coding Agent](../features/CODING_AGENT.md) shows the interactive approval UX
    (allow once / always / deny).

    ## Agent tools (`raxol_agent`)

    #{table(agent)}

    ## Payment tools (`raxol_payments`)

    #{table(payments)}
    """
  end

  defp table(metas) do
    header =
      "| Tool | Sensitive | Description | Parameters |\n" <>
        "|------|:---:|-------------|------------|"

    rows =
      Enum.map_join(metas, "\n", fn m ->
        "| `#{m.name}` | #{if m.sensitive, do: "yes", else: "no"} | #{escape(m.description)} | #{m.params} |"
      end)

    header <> "\n" <> rows
  end

  # --- helpers --------------------------------------------------------------

  defp one_line(text) do
    text
    |> to_string()
    |> String.replace(~r/\s+/, " ")
    |> String.trim()
  end

  defp escape(text), do: String.replace(text, "|", "\\|")

  defp repo_root do
    candidate = Path.expand(Path.join([File.cwd!(), "..", ".."]))

    if File.dir?(Path.join(candidate, "docs")) do
      candidate
    else
      Mix.raise(
        "docs/ not found above #{File.cwd!()}. Run this task from " <>
          "packages/raxol_payments in a full raxol checkout (mix raxol.docs.tools)."
      )
    end
  end
end
