#!/usr/bin/env bash
# gen_homebrew_formula.sh -- emit the Homebrew formula for a published release.
#
#   scripts/gen_homebrew_formula.sh 0.2.6 > raxol.rb
#
# Writes to stdout. Copy the result into the tap repo
# (DROOdotFOO/homebrew-tap, as Formula/raxol.rb) so users can:
#
#   brew install droodotfoo/tap/raxol
#
# Checksums are read from the release's own SHA256SUMS rather than kept in the
# repo: a formula with hand-copied hashes is a formula that goes stale silently,
# and Homebrew's failure mode for a wrong hash is an unhelpful mid-download
# abort.
#
# Windows is intentionally absent (Homebrew targets macOS and Linux), and
# macOS x86_64 is absent because the release does not publish one.

set -euo pipefail

REPO="DROOdotFOO/raxol"
TAG_PREFIX="raxol-cli-v"

version="${1:-}"
if [[ -z "$version" ]]; then
  printf 'usage: %s <version>\n' "$0" >&2
  exit 64
fi

tag="${TAG_PREFIX}${version}"
base="https://github.com/$REPO/releases/download/$tag"

sums=$(curl -fsSL "$base/SHA256SUMS") ||
  { printf 'error: no SHA256SUMS for %s\n' "$tag" >&2; exit 1; }

sha_for() {
  local name="$1" sha
  sha=$(printf '%s\n' "$sums" | awk -v b="$name" '$2 == b || $2 == "*" b {print $1}' | head -n 1)
  [[ -n "$sha" ]] || { printf 'error: no checksum for %s in %s\n' "$name" "$tag" >&2; exit 1; }
  printf '%s' "$sha"
}

macos_arm=$(sha_for raxol_cli_macos)
linux_x64=$(sha_for raxol_cli_linux)
linux_arm=$(sha_for raxol_cli_linux_arm)

cat <<FORMULA
# Generated by scripts/gen_homebrew_formula.sh -- do not hand-edit.
class Raxol < Formula
  desc "Interactive AI agent and TUI toolkit for the terminal"
  homepage "https://raxol.io"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/raxol_cli_macos"
      sha256 "$macos_arm"

      def install
        bin.install "raxol_cli_macos" => "raxol"
      end
    end
  end

  on_linux do
    on_intel do
      url "$base/raxol_cli_linux"
      sha256 "$linux_x64"

      def install
        bin.install "raxol_cli_linux" => "raxol"
      end
    end

    on_arm do
      url "$base/raxol_cli_linux_arm"
      sha256 "$linux_arm"

      def install
        bin.install "raxol_cli_linux_arm" => "raxol"
      end
    end
  end

  def caveats
    <<~EOS
      raxol ships its own Erlang runtime, so no Elixir install is needed.
      On first run it unpacks that payload to ~/.cache/burrito (Linux) or
      ~/Library/Application Support/.burrito (macOS).

      Connect an LLM provider before first use:
        raxol setup --provider anthropic --op op://Vault/Item/api_key

      Check what this install resolves:
        raxol doctor
    EOS
  end

  test do
    assert_match "raxol", shell_output("#{bin}/raxol --help")
  end
end
FORMULA
