defmodule Raxol.ACP.Wallet.SCA.ProvisioningTest do
  use ExUnit.Case, async: true

  alias Raxol.ACP.ABI
  alias Raxol.ACP.Wallet.SCA.{ModularAccount, Provisioning}

  @owner "0x9a96e767bfcce8e80370be00821ed5ba283d4a17"

  describe "predict_address/2" do
    # Reference addresses generated by Account Kit's
    # predictModularAccountV2Address (SMA) replicated with viem 2.51.3:
    #
    #   getContractAddress({ from: factory, opcode: "CREATE2",
    #     salt: keccak256(encodePacked(["address","uint256","uint32"],
    #       [owner, salt, 0xffffffff])),
    #     bytecode: proxyWithImmutableArgs(smaBytecode, owner) })
    test "matches the Account Kit / viem counterfactual SMA address (salt 0)" do
      assert Provisioning.predict_address(@owner, 0) ==
               "0xcfba4d9139768f108a648efe148de5474d258765"
    end

    test "matches for a nonzero salt" do
      assert Provisioning.predict_address(@owner, 7) ==
               "0xf13663d3642a64644015f3387ab9f30809de8844"
    end

    test "defaults salt to 0" do
      assert Provisioning.predict_address(@owner) == Provisioning.predict_address(@owner, 0)
    end

    test "is deterministic and 0x-prefixed 20-byte hex" do
      addr = Provisioning.predict_address(@owner)
      assert String.starts_with?(addr, "0x")
      assert byte_size(addr) == 42
      assert addr == Provisioning.predict_address(@owner)
    end

    test "different owners yield different addresses" do
      other = "0x" <> String.duplicate("11", 20)
      assert Provisioning.predict_address(@owner) != Provisioning.predict_address(other)
    end
  end

  describe "deploy_init_code/2" do
    test "is factory address ++ createSemiModularAccount(owner, salt) calldata" do
      init_code = Provisioning.deploy_init_code(@owner, 0)

      <<factory::binary-size(20), call_data::binary>> = init_code

      assert "0x" <> Base.encode16(factory, case: :lower) ==
               String.downcase(ModularAccount.factory_address())

      expected =
        ABI.encode_call("createSemiModularAccount(address,uint256)", [
          {"address", @owner},
          {"uint256", 0}
        ])

      assert call_data == expected
    end

    test "the factory call selector matches createSemiModularAccount" do
      <<_factory::binary-size(20), selector::binary-size(4), _rest::binary>> =
        Provisioning.deploy_init_code(@owner, 0)

      expected = binary_part(ExKeccak.hash_256("createSemiModularAccount(address,uint256)"), 0, 4)
      assert selector == expected
    end

    test "encodes the salt" do
      <<_factory::binary-size(20), _selector::binary-size(4), owner_word::binary-size(32),
        salt_word::binary-size(32)>> = Provisioning.deploy_init_code(@owner, 42)

      assert <<0::96, owner_bytes::binary-size(20)>> = owner_word
      assert "0x" <> Base.encode16(owner_bytes, case: :lower) == @owner
      assert <<salt::unsigned-big-256>> = salt_word
      assert salt == 42
    end
  end
end
