defmodule Raxol.Payments.Test.ConformanceFixture do
  @moduledoc """
  Loader for the shared EIP-712 conformance fixture.

  The fixture file lives in the `riddler-client` monorepo at
  `packages/spec/conformance/conformance.json` (the `@riddler/spec`
  package) and is the byte-equality contract between the Node SDK and
  `raxol_payments`. It is generated by `npm run generate:conformance`
  in the CLI repo.

  Resolves the fixture path via:

  1. `CONFORMANCE_FIXTURE_PATH` env var (explicit override)
  2. `RIDDLER_CLI_DIR` env var (CLI repo root)
  3. Sibling fallback `../../../../riddler-client`

  Conformance tests are tagged `:conformance` (also `:cli_signer` via the
  same fixture path requirement) and are skipped by default when no
  fixture can be located.
  """

  @doc """
  Load the entire fixture as a list of vector maps. Raises if the
  fixture cannot be found.
  """
  @spec load!() :: [map()]
  def load! do
    path = locate_path!()
    path |> File.read!() |> Jason.decode!()
  end

  @doc """
  Filter the fixture by `"protocol"` field.

  Returns `[]` when the fixture is absent, rather than raising. The conformance
  files call this at test-module COMPILE time (`for vec <- by_protocol(...)`
  inside a `describe`), so the `:conformance` moduletag -- a runtime exclusion --
  cannot save a raise here: the whole suite dies before a single test runs. That
  is what kept `raxol_payments` out of CI, where riddler-client is not checked
  out beside the repo.

  The absence is announced rather than swallowed: generating zero vectors is
  legitimate here, but it must not look like coverage that passed.
  """
  @spec by_protocol(String.t()) :: [map()]
  def by_protocol(protocol) do
    case do_locate() do
      nil ->
        IO.puts(
          :stderr,
          "[conformance] fixture absent -- 0 #{protocol} vectors generated. " <>
            "Set CONFORMANCE_FIXTURE_PATH or RIDDLER_CLI_DIR to run them."
        )

        []

      _path ->
        Enum.filter(load!(), &(&1["protocol"] == protocol))
    end
  end

  @doc "Return the single vector with the given `\"name\"`."
  @spec by_name(String.t()) :: map() | nil
  def by_name(name) do
    Enum.find(load!(), &(&1["name"] == name))
  end

  @doc """
  Try to locate the fixture file. Returns `{:ok, path}` or `{:error, :not_found}`
  without raising. Useful in `setup` blocks that conditionally skip tests.
  """
  @spec locate() :: {:ok, Path.t()} | {:error, :not_found}
  def locate do
    case do_locate() do
      nil -> {:error, :not_found}
      path -> {:ok, path}
    end
  end

  # -- Internals --

  defp locate_path! do
    case do_locate() do
      nil ->
        raise "Conformance fixture not found. Set CONFORMANCE_FIXTURE_PATH " <>
                "or RIDDLER_CLI_DIR, or place riddler-client beside the raxol repo."

      path ->
        path
    end
  end

  defp do_locate do
    candidates =
      [
        System.get_env("CONFORMANCE_FIXTURE_PATH"),
        cli_dir_path(System.get_env("RIDDLER_CLI_DIR")),
        cli_dir_path(sibling_default())
      ]
      |> Enum.reject(&is_nil/1)

    Enum.find(candidates, &File.exists?/1)
  end

  defp cli_dir_path(nil), do: nil

  defp cli_dir_path(dir),
    do: Path.join([dir, "packages", "spec", "conformance", "conformance.json"])

  # axol-io/riddler-sdk, formerly riddler-client. The old name is kept as a
  # fallback so a checkout under either directory resolves.
  defp sibling_default do
    Enum.find(
      [
        Path.expand("../../../../../riddler-sdk", __DIR__),
        Path.expand("../../../../../riddler-client", __DIR__)
      ],
      &File.dir?/1
    )
  end
end
